# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: required
cache: packages

# https://github.com/ropensci/rgbif/blob/master/.travis.yml#L9
dist: trusty

after_success:
  - Rscript -e 'covr::codecov()'